services:
  
  ncat_server:
    container_name: ncat_server
    hostname: ncat_server
    image: my-gcc-app
    #build: .
    volumes:
      - ".:/workspace"
    ports:
      - 8080:8080
    #command: "nc -l -p 8080"
  
  java_client:
    image: my-gcc-app
    #build: .
    volumes:
      - ".:/workspace"
    working_dir: /workspace/java_code
    command: "java eu.vctl.wfis.SimpleClient ncat_server:8080 JabberWooky"
  
  python_client:
    image: my-gcc-app
    #build: .
    volumes:
      - ".:/workspace"
    working_dir: /workspace/python_code
    #command: "python3 SimpleClientSockAPI.py ncat_server:8080 JabberWooky_python"

  flask_server:
    hostname: flask_server
    image: my-gcc-app
    #build: .
    volumes:
      - ".:/workspace"
    ports:
      - "5000:5000"
    working_dir: /workspace/python_code
    command: "flask run --host=0.0.0.0"
  
  mariadb:
    image: mariadb
    hostname: mariadb
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: appdb
      MYSQL_ROOT_PASSWORD: abc123
    volumes:
      - "./mariadb/:/docker-entrypoint-initdb.d"

  pgsql:
    image: postgres
    hostname: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: passABC
    volumes:
      #- pgdata:/var/lib/postgresql/data
      - "./pgsql/pracownicy.sql:/tmp/pracownicy.sql"
      - "./pgsql/init_db.sh:/docker-entrypoint-initdb.d/init-db.sh"

  jdbc_client:
    image: my-gcc-app
    #build: .
    volumes:
      - ".:/workspace"
    working_dir: /workspace/java_code
    environment:
      - DB_ADDRESS=postgres
    command: "java -classpath \".:./postgresql-42.7.5.jar\" eu.vctl.wfis.PgSQLClient"

