version: '1.0'
services:
  
  ncat_server:
    container_name: ncat_server
    hostname: ncat_server
    image: my-gcc-app
    #build: .
    volumes:
      - ".:/workspace"
    ports:
      - 8080:8080
    #command: "nc -l -p 8080"
  
  java_client:
    image: my-gcc-app
    #build: .
    volumes:
      - ".:/workspace"
    working_dir: /workspace/java_code
    command: "java eu.vctl.wfis.SimpleClient ncat_server:8080 JabberWooky"
  
  python_client:
    image: my-gcc-app
    #build: .
    volumes:
      - ".:/workspace"
    working_dir: /workspace/python_code
    #command: "python3 SimpleClientSockAPI.py ncat_server:8080 JabberWooky_python"

  flask_server:
    container_name: flask_server
    hostname: flask_server
    image: my-gcc-app
    #build: .
    volumes:
      - ".:/workspace"
    ports:
      - 5000:5000
